// <auto-generated>
// Rewired Constants
// This list was generated on 2/17/2026 11:00:28 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // UI
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "MoveHorizontal")]
        public const int MoveHorizontal = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "MoveVertical")]
        public const int MoveVertical = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "BasicAttack")]
        public const int BasicAttack = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Skill1")]
        public const int Skill1 = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Skill2")]
        public const int Skill2 = 4;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Skill3")]
        public const int Skill3 = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Skill4")]
        public const int Skill4 = 6;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
        public const int Gameplay = 1;
        
        public const int UI = 2;
        
    }
    public static partial class MapEnablerRuleSet {
    }
}
