// <auto-generated>
// Rewired Constants
// This list was generated on 2/16/2026 12:10:47 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // UI
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "MoveHorizontal")]
        public const int MoveHorizontal = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "MoveVertical")]
        public const int MoveVertical = 1;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
        public const int Gameplay = 1;
        
        public const int UI = 2;
        
    }
    public static partial class MapEnablerRuleSet {
    }
}
